**Content:** Aiyagari model with difussion process and Deep Learning

**Author:** Marco Piña

**Date:** Nov-2021

In [2]:
import tensorflow as tf 
from tensorflow import keras

In [8]:
alpha = tf.constant(0.35)
beta  = tf.constant(1.05**(-1/4))
rho   = tf.constant(0.05)
delta = tf.constant(0.1)
gamma = tf.constant(2)
phi   = tf.constant(-1)
Delta = tf.constant(1000)
Na    = tf.constant(100) #100
Nz    = tf.constant(40) #40

batchSize = 100                    # Batch Size
number_epochs = 100000             # Number of epochs

kMin = 0.1                         # lower bound of sample interval
kMax = 10.0                        # upper bound of sample interval

gridSize = 10000                  # Plotting grid

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.7951286 , 0.5510745 , 0.12180364, 0.89232135],
       [0.5489644 , 0.40709484, 0.03784883, 0.14281535],
       [0.47531617, 0.04792309, 0.20777798, 0.61168075]], dtype=float32)>

In [11]:
#tf.reshape(tensor= array, shape = [4,3])
tf.transpose(array)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.7951286 , 0.5489644 , 0.47531617],
       [0.5510745 , 0.40709484, 0.04792309],
       [0.12180364, 0.03784883, 0.20777798],
       [0.89232135, 0.14281535, 0.61168075]], dtype=float32)>